### ISSUE TITLE
Need pretrained model

### ISSUE THREAD

**Issue by ajaysurya1221** [Zce1112zslx/KID#1]
Hi, @Zce1112zslx. could you please share with me your best checkpoint?

**Comment by Zce1112zslx** [comment]
Hi, @ajaysurya1221 !
Here is the link to download our trained models.
https://drive.google.com/drive/folders/1YcWJfDRdtrp0FFn9iB9E0O4ajD5yYMxT?usp=sharing

**Comment by ajaysurya1221** [comment]
Thanks, @Zce1112zslx, I owe you one. :)
