### ISSUE TITLE
Is there a difference in the assessment of core/non-core FEs?

### ISSUE THREAD

**Issue by Dr-Corgi** [Zce1112zslx/KID#3]
Hi @Zce1112zslx ,
I would like to know why the fn/fp calculating strategy for core and non-core Frame Element are different (`in the evaluation.py`), see:
```
(line66-71)
                if fe_coretype[int(gold_fe_type[batch_index][fe_index])] == 1:
                    self.fe_TP_FN+=1
                    self.core_cnt+=1
                else:
                    self.fe_TP_FN+=0.5
                    self.nocore_cnt+=1
```

I'd like to know if there is a standard evaluation script for such calculations, or whether there are some existing works that counting the score of  non-core FEs as 0.5. Thank you very much!

**Comment by Dr-Corgi** [comment]
I found the answer on: https://github.com/Noahs-ARK/semafor/blob/master/scripts/scoring/fnSemScore_modified.pl

**Comment by Dr-Corgi** [comment]
I found the answer on: https://github.com/Noahs-ARK/semafor/blob/master/scripts/scoring/fnSemScore_modified.pl

thank you.

**Comment by Zce1112zslx** [comment]
Yes our evaluation code is a re-implementation python version of SEMAFOR. You can also use the perl version if you are familar with it.
